version: "3.8"
services:
  react:
    build: .
    container_name: react
    ports:
      - "3000:80"
    restart: on-failure
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  
      - ./build:/usr/share/nginx/html
    restart: on-failure